### ISSUE TITLE
Add configurable service path

### ISSUE THREAD

**Issue by levicoradine** [bitnami/bitnami-docker-testlink#118]
**Description**

Presently the image is configured to serve the testlink application from `\` but it would be beneficial to provide this as a configuration option via environment variable.

There are request to serve from an alternate location already. See https://github.com/bitnami/bitnami-docker-testlink/issues/54 and https://github.com/bitnami/bitnami-docker-testlink/issues/70

Currently the only way to accommodate this is to augment (or supply a new version) of the apache config files (see mentioned issues). This is problematic when trying to deploy on AWS Fargate as there is no way to post process the install, nor mount a new configuration file over the existing file (Fargate only supports EFS volumes not Bind Mounts). The only remaining option is to extend this container with a new Dockerfile to install the appropriate apache config.

Adding an environment variable for the path to serve the testlink application would be a clean and elegant solution.

**Comment by carrodher** [comment]
Yeah, it sounds like a good feauture. As all the code is available in this repository, would you like to contribute to this feature? Otherwise, I will create an internal task to be added to our backlog, although I can't provide you an ETA for this task since it is going to depend on the team bandwidth and other priorities.

**Comment by levicoradine** [comment]
@carrodher Thanks for your consideration. Unfortunately I doubt I'll have any time to dedicate to this anytime soon so please add it to the backlog. Cheers.

**Comment by carrodher** [comment]
Nice, I just created the internal task on our side. I'm setting the `on-hold` label to prevent the stale-bot from closing this issue. Although as I mentioned in the previous comment, I can't provide an ETA for this task since it depends on other priorities the team has. Thanks!

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-testlink#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
