### ISSUE TITLE
realpath: /bitnami/apache/conf: No such file or directory

### ISSUE THREAD

**Issue by Saisco** [bitnami/bitnami-docker-testlink#123]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by migruiz4** [comment]
Hi @Saisco,

Please fulfill the issue template and include more information about your problem, otherwise, we may not be able to help you.

We need more details about your issue in order to help you: which chart you are using and its version, values being used to deploy, how did you run into this issue and steps to reproduce if possible, a section of logs and/or output of any command that may be helpful to help us determine the cause of the issue, etc.
