### ISSUE TITLE
Cant save attachments in execution steps/No "Save Execution" button.

### ISSUE THREAD

**Issue by yves219** [bitnami/bitnami-docker-testlink#91]
In version 1.9.19.
No save button for steps notes and status.
Saving Test Case execution status does not save steps notes and status.
Step notes and step status are lost when test case execution status is saved.

In version 1.9.14 you have the "save execution" button. In version 1.9.19 it does not. Where can I get information about this? How does it work now?

**Comment by andresbono** [comment]
Hi @yves219, it seems it is a known issue. Can you take a look at this bug report?: http://mantis.testlink.org/view.php?id=8586

**Comment by yves219** [comment]
Hi @andresbono that's my main concern
http://mantis.testlink.org/view.php?id=8492
Saving Test Case execution status does not save steps notes and status.
![000000](https://user-images.githubusercontent.com/59615411/71967558-7f1a1b80-323e-11ea-96d9-ed06355db290.PNG)

**Comment by andresbono** [comment]
I'm afraid there is not so much we can do on our side. Do you think the issue is related to the way the application is configured or packaged?

I suggest you to ask for more information in the testlink bug tracker. Maybe you get some errors in your browser console that may help to find the cause of the issue.
